version: '3'

silent: true

tasks:

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo +stable build

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo +stable clean

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +stable clippy --all-targets

  fmt:
    desc: Runs code formatter
    cmds:
      - cmd: cargo +nightly fmt

  install:
    desc: Builds and installs release version from local sources
    cmds:
      - cmd: cargo +stable install wasm-compilation-time --path . --force

  run:
    desc: Runs all tests
    cmds:
      - cmd: cargo +stable build --release --features=wasmer
      - cmd: ./target/release/wasm-compilation-time wasmer-cranelift-none
      - cmd: ./target/release/wasm-compilation-time wasmer-cranelift-speed
      - cmd: ./target/release/wasm-compilation-time wasmer-singlepass
      - cmd: cargo +stable build --release --features=wasmtime
      - cmd: ./target/release/wasm-compilation-time wasmtime-cranelift-none
      - cmd: ./target/release/wasm-compilation-time wasmtime-cranelift-speed
      - cmd: ./target/release/wasm-compilation-time wasmtime-singlepass
      - cmd: cargo +stable build --release --features=cosmwasm
      - cmd: ./target/release/wasm-compilation-time cosmwasm-singlepass
